implemented crud function for employees page
carrieayu/bop pull request #150
Opened 2024-09-26 05:49 UTC by merlouduron

# Pull Request Review Comments

## Overview
- **Purpose of the PR**:
    - [ ] Feature addition
    - [ ] Bug fix
    - [ ] Refactoring
    - [ ] Documentation update
    - [ ] Other (please specify below)

## Specific Areas for Verification
- Please specify any particular requests or questions for the reviewer here.

## Suggestions/Concerns
- If you have any suggestions or concerns, please mention them here.

---

_**Additional Comments for the Reviewer (Optional)**_

- Add any additional comments or information for the reviewer here.

2024-09-26 06:19 UTC, edward-stalley-work requested changes
Please check when you have time!

2024-09-26 06:19 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +        }))
Is there a way for it to not be an AbstractBaseUser? Or will this cause complications?
Could it not just be a regular model?

Both password and last_login are not necessary in 'employees' and could cause confusion in the DB.
![Screenshot 2024-09-26 at 15 17 02](https://github.com/user-attachments/assets/701ceccf-d0a1-468a-ab0e-3086b35a9d37)

2024-09-26 06:19 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +          auth_user: 1,
auth_user is hardcoded: Should be whomever is logged in currently.

2024-09-26 06:19 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +              <p className='EmployeesRegistration_form-title'>{translate('employeesRegistration', language)}</p>
従業員登録 is displayed twice.

![Screenshot 2024-09-26 at 15 06 05](https://github.com/user-attachments/assets/f607020f-9377-43ae-ba63-990bad4c1fe7)

2024-09-26 06:19 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +
I was able to make an employee with identical email address.

![Screenshot 2024-09-26 at 15 08 08](https://github.com/user-attachments/assets/794a7574-4fb9-46f9-a655-0fe979996628)

2024-09-26 06:19 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesListAndEdit.tsx
> +                                      onChange={(e) => handleChange(employeeIndex, e)}
- There is whitespace instead of the previously selected business division.
 - previously selected business division.is not displayed in edit mode.

![Screenshot 2024-09-26 at 15 09 37](https://github.com/user-attachments/assets/0acd455b-c256-4bf5-9a0b-7b92b3cf9389)

2024-09-26 06:19 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesListAndEdit.tsx
> +                                          {company.company_name}
- There is whitespace instead of the previously selected company.
 - previously selected company name is not displayed in edit mode.

![Screenshot 2024-09-26 at 15 09 37](https://github.com/user-attachments/assets/0acd455b-c256-4bf5-9a0b-7b92b3cf9389)

2024-09-26 06:19 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesListAndEdit.tsx
> +        setDeleteUserId(id)
1.
Should this not be `setDeleteEmployeeId`? 

2.
Also the modal says client 顧客 not employee 従業員

この顧客を削除してもよろしいですか？ 
→
この従業員を削除してもよろしいですか？

2024-09-26 08:57 UTC, merlouduron commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +import { fetchBusinessDivisions } from '../../reducers/businessdivisions/businessdivisionsSlice'
Fixed.

2024-09-26 08:57 UTC, merlouduron commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +        }))
I tried changing it to normal model and tested it (Also test the login using registered user from user registration) and it's working so I decided to change it to normal model.

2024-09-26 08:57 UTC, merlouduron commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +          auth_user: 1,
Fixed.

2024-09-26 08:57 UTC, merlouduron commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +              <p className='EmployeesRegistration_form-title'>{translate('employeesRegistration', language)}</p>
Fixed.

2024-09-26 08:57 UTC, merlouduron commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +
Fixed.

2024-09-26 08:57 UTC, merlouduron commented on client/src/pages/Employees/EmployeesListAndEdit.tsx
> +                                      onChange={(e) => handleChange(employeeIndex, e)}
Fixed.

2024-09-26 08:57 UTC, merlouduron commented on client/src/pages/Employees/EmployeesListAndEdit.tsx
> +                                          {company.company_name}
Fixed.

2024-09-26 08:57 UTC, merlouduron commented on client/src/pages/Employees/EmployeesListAndEdit.tsx
> +        setDeleteUserId(id)
Fixed.

2024-09-27 00:05 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +import { fetchBusinessDivisions } from '../../reducers/businessdivisions/businessdivisionsSlice'
Thank you Merlou. However, the directory does not look changed on my end.

![Screenshot 2024-09-27 at 09 05 21](https://github.com/user-attachments/assets/92fad340-64a6-415b-9367-a58aeb7f9cce)

2024-09-27 00:10 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +import { fetchBusinessDivisions } from '../../reducers/businessdivisions/businessdivisionsSlice'
I get this error as well which seems related.

![Uploading Screenshot 2024-09-26 at 18.01.21.png…]()

2024-09-27 01:01 UTC, edward-stalley-work requested changes
Thank you for your fixes Merlou.
There is still one or two things that need to be rechecked and I have also added a few new comments.

2024-09-27 01:01 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
>            last_name: empl.last_name,
is it possible to have all entries in the database be lowercase?

So no matter what I register:
Eg.
```
Last Name: 'Jones'
First Name:'TOM' 
```

IN DB

```
Last Name: 'jones'
First Name:'tom' 
```

For English names it is normal to have capital first letters. When displayed in any List/Edit screens could we do a string check so that they display like below?

```
Last Name: 'Jones'
First Name:'Tom' 
```

So DB: ALL lowercase.
Display: Capital 1st letter of each name.

2024-09-27 01:15 UTC, edward-stalley-work commented
The update button is also very far down the page in ListAndEdit Screen. Often have to scroll down to see it. Could we bring it up?

2024-09-27 02:23 UTC, merlouduron commented on client/src/pages/Employees/EmployeesRegistration.tsx
>            last_name: empl.last_name,
Fixed.

2024-09-27 02:23 UTC, merlouduron commented on client/src/translations/general_words_jp.json
> +    "email2": "このメールはすでに存在している。",
Fixed.

2024-09-27 02:23 UTC, merlouduron commented on client/src/translations/general_words_jp.json
> +    "deleteMessage2": "この従業員を削除してもよろしいですか？",
Fixed.

2024-09-27 02:23 UTC, merlouduron commented on client/src/translations/general_words_jp.json
>      "deleteMessage": "この顧客を削除してもよろしいですか？",
Fixed.

2024-09-27 02:23 UTC, merlouduron commented on client/src/translations/general_words_en.json
> +    "email2": "This email already exist.",
Fixed.

2024-09-27 02:23 UTC, merlouduron commented on client/src/translations/general_words_en.json
> +    "deleteMessage2": "Are you sure you would like to delete this employee?",
Fixed.

2024-09-27 02:23 UTC, merlouduron commented on client/src/translations/general_words_en.json
>      "deleteMessage": "Are you sure you would like to delete this client?",
Fixed.

2024-09-27 02:23 UTC, merlouduron commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +import { fetchBusinessDivisions } from '../../reducers/businessdivisions/businessdivisionsSlice'
For this error, you need to stop the build both frontend and backend. After that you need to execute `npm run build` command. After finishing the build, execute `npm run dev` , close the old tab and create new tab. Open localhost:8000/login then log-in the credentials. If it still getting error, please tell me and I'll fix it right away. 🙇

2024-09-27 04:16 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +import { fetchBusinessDivisions } from '../../reducers/businessdivisions/businessdivisionsSlice'
Thank you Merlou. The actual directory file name needs to be updated as well. That seems to solve the issue. So please do that.

Current:
![Screenshot 2024-09-27 at 13 10 54](https://github.com/user-attachments/assets/d24b25ab-7cff-47f4-a9ba-ec9c20cd2ee4)

Needs to be updated to this:
![Screenshot 2024-09-27 at 13 08 50](https://github.com/user-attachments/assets/25077876-f717-4eb8-8651-5de21e25eb2c)

2024-09-27 04:30 UTC, edward-stalley-work commented
The screen is cutting off a little between the 4 tabs and the cancel/register buttons. Think the height needs to be increased slightly.

![Screenshot 2024-09-27 at 13 29 31](https://github.com/user-attachments/assets/cb8e0ef8-5894-4513-8467-61a2eeb47de3)

2024-09-27 04:31 UTC, edward-stalley-work commented
When adding multiple employees it is unclear when 1 employee ends and the next starts. Could be good to add a line as a divider.

![Screenshot 2024-09-27 at 13 30 52](https://github.com/user-attachments/assets/c51659ab-83fe-478d-9402-36e0a66e81dc)
![Screenshot 2024-09-27 at 13 31 40](https://github.com/user-attachments/assets/3a6524e3-dbc4-462c-9bbd-220c381659fd)

2024-09-27 06:27 UTC, edward-stalley-work requested changes
Please see comments

2024-09-27 06:27 UTC, edward-stalley-work commented on backend/backend/urls.py
> +    path('api/employees/update/', UpdateEmployee.as_view()),
Employees is not following the pattern.
Why is list in there!? 
Is this not possible?

`'api/employees/<int:pk>/delete/', EmployeesDelete.as_view()
`
Update function can actually update more than one employee record so maybe having <int:pk> makes no sense?
`    path('api/employees/<int:pk>/update/', UpdateEmployee.as_view()),
`

Could the class names follow this convention
Name + Function

Class should be:
EmployeesCreate
EmployeesDelete
EmployeesUpdate

2024-09-27 06:27 UTC, edward-stalley-work commented on client/src/assets/scss/Employees/EmployeesRegistration.scss
> +                        opacity: 30%;
Is it possible to have it like this? (shorter on right side so its in line with input box)

<img width="841" alt="Screenshot 2024-09-27 at 15 24 43" src="https://github.com/user-attachments/assets/e9fc8a09-c8dc-462b-ade5-2116c659e02f">

2024-09-30 00:50 UTC, edward-stalley-work requested changes
Please see comments

2024-09-30 00:50 UTC, edward-stalley-work commented on backend/api/models.py
>              self.employee_id = self._generate_employee_id()
Changed back to original.(fixed)

(please remember to do final comment like this or 'fixed') 
It really helps me to know if it has been seen/addressed.

2024-09-30 00:50 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesListAndEdit.tsx
> +        const response = await axios.delete(`http://127.0.0.1:8000/api/employees/${deleteId}/delete/`, {
This works now - thank you.

However the update function needs a fix.
Right now if I change to duplicate email on edit page the update will fail (correct).
However no indication is given to the user. (No Modal appears.)

![Screenshot 2024-09-30 at 09 37 23](https://github.com/user-attachments/assets/82e895eb-b752-45e2-b16f-2c05fdc5abb2)

On the registration page there is a modal (correct)
Please make sure the edit page also has a modal like the registration page.

![Screenshot 2024-09-30 at 09 37 57](https://github.com/user-attachments/assets/091a4304-a767-4c0b-808e-a10da9301ad4)

2024-09-30 00:50 UTC, edward-stalley-work commented on client/src/assets/scss/Employees/EmployeesRegistration.scss
> +                        opacity: 30%;
fixed

2024-09-30 01:31 UTC, merlouduron commented on client/src/pages/Employees/EmployeesListAndEdit.tsx
> +        const response = await axios.delete(`http://127.0.0.1:8000/api/employees/${deleteId}/delete/`, {
Fixed.

2024-09-30 01:57 UTC, merged