fix be for business division create and list
carrieayu/bop pull request #152
Opened 2024-09-30 02:40 UTC by ian-bpoc

# Pull Request Review Comments

## Overview
- **Purpose of the PR**:
    - [/ ] Bug fix
    - [/ ] Refactoring

## Specific Areas for Verification
- Please specify any particular requests or questions for the reviewer here.

## Suggestions/Concerns
- If you have any suggestions or concerns, please mention them here.

---

_**Additional Comments for the Reviewer (Optional)**_

- I temporarily add the alert text for the duplicated entry of business name

2024-09-30 03:40 UTC, edward-stalley-work reviewed
Thank you Ian please see comment!

2024-09-30 03:40 UTC, edward-stalley-work commented on client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
> +        // const response = await axios.put('http://54.178.202.58:8000/api/projectdatalist/update/',  changes ,{
Edit seems to not be working right now. Always gives duplicate error.




<img width="571" alt="Screenshot 2024-09-30 at 12 27 17" src="https://github.com/user-attachments/assets/a7b565b5-48e9-4cf7-8710-3a0f44706e1c">

2024-09-30 03:41 UTC, ian-bpoc commented on client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
> +        // const response = await axios.put('http://54.178.202.58:8000/api/projectdatalist/update/',  changes ,{
I will take a look on it Ed

2024-10-01 02:30 UTC, edward-stalley-work requested changes
Thank you Ian.
Please see comments.

Summary:
When I opened your branch I had a lot of BusinessDivisionSlice errors.
This is due to lowercase instead of camelcase.

Also clients does not work on your branch so you need to pull the latest changes from develop and deal with any conflicts on your end.

Finally please add delete button/function!

2024-10-01 02:30 UTC, edward-stalley-work commented on client/src/app/store.ts
> +import businessDivisionsSlice from "../reducers/businessdivisions/businessdivisionsSlice";
This should be camelCase.
`businessDivisions/businessDivisionsSlice`

2024-10-01 02:30 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesListAndEdit.tsx
> +import { fetchBusinessDivisions } from "../../reducers/businessdivisions/businessdivisionsSlice";
This should be camelCase.
businessDivisions/businessDivisionsSlice

2024-10-01 02:30 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +import { fetchBusinessDivisions } from '../../reducers/businessdivisions/businessdivisionsSlice'
This should be camelCase.
businessDivisions/businessDivisionsSlice

2024-10-01 02:30 UTC, edward-stalley-work commented on client/src/pages/BusinessDivisions/BusinessDivisionsRegistration.tsx
> +            alert('Business Name Already Exist')
Please add an 's' and remove capitals except for first 'B'.

`Business name already exists`

2024-10-01 02:30 UTC, edward-stalley-work commented on client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
> +                              ))}
No delete functionality right now. Please add a trash bin and delete like the other Edit pages!

![Screenshot 2024-10-01 at 11 28 30](https://github.com/user-attachments/assets/c87085ce-3ef3-4542-b0f8-f32e72e2ba2e)

Example from Employees
![Screenshot 2024-10-01 at 11 28 59](https://github.com/user-attachments/assets/6e8dc6d1-c55a-4a98-9ad1-d306f2de60f8)

2024-10-01 03:31 UTC, ian-bpoc commented on client/src/app/store.ts
> +import businessDivisionsSlice from "../reducers/businessdivisions/businessdivisionsSlice";
already fix the path into CamelCase and revert current changes

2024-10-01 03:31 UTC, ian-bpoc commented on client/src/pages/Employees/EmployeesListAndEdit.tsx
> +import { fetchBusinessDivisions } from "../../reducers/businessdivisions/businessdivisionsSlice";
already fix the path into CamelCase and revert current changes

2024-10-01 03:31 UTC, ian-bpoc commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +import { fetchBusinessDivisions } from '../../reducers/businessdivisions/businessdivisionsSlice'
already fix the path into CamelCase and revert current changes

2024-10-01 03:42 UTC, ian-bpoc commented on client/src/pages/BusinessDivisions/BusinessDivisionsRegistration.tsx
> +            alert('Business Name Already Exist')
included on my new commit https://github.com/carrieayu/bop/pull/152/commits/bcabfd06b2ab4ef03072c8a5e806f396591958cb together with reverting the file format

2024-10-01 06:29 UTC, ian-bpoc commented on client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
> +                              ))}
added commit on delete function

2024-10-01 07:47 UTC, edward-stalley-work requested changes
Please see comments

2024-10-01 07:47 UTC, edward-stalley-work commented on client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
> +          // },
This is all commented out? Think this is the cause of update button not working and going to login.

2024-10-01 07:47 UTC, edward-stalley-work commented on client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
> +            // },
why is this commented out?
If its not needed please remove .

2024-10-01 07:47 UTC, edward-stalley-work commented on backend/api/views.py
> +    # lookup_field = 'pk'
why are these commented out?
If its not needed please remove .

2024-10-01 07:47 UTC, edward-stalley-work commented on backend/api/urls.py
>      # path("master-business-division/<int:pk>/update/", views.MasterBusinessDivisionUpdate.as_view(), name="master-business-division-update"), #temporary commented currently using bulk-update
why is this commented out?
If its not needed please remove .

2024-10-01 07:52 UTC, ian-bpoc commented on backend/api/urls.py
>      # path("master-business-division/<int:pk>/update/", views.MasterBusinessDivisionUpdate.as_view(), name="master-business-division-update"), #temporary commented currently using bulk-update
already remove in my latest commit Ed

2024-10-01 07:52 UTC, ian-bpoc commented on backend/api/views.py
> +    # lookup_field = 'pk'
already removed the commented code

2024-10-01 07:52 UTC, ian-bpoc commented on client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
> +            // },
uncommented code

2024-10-01 07:53 UTC, ian-bpoc commented on client/src/pages/BusinessDivisions/BusinessDivisionsListAndEdit.tsx
> +          // },
done uncommented the code

2024-10-01 08:02 UTC, merged