modify the position of company and business dropdown
carrieayu/bop pull request #157
Opened 2024-10-03 08:08 UTC by ian-bpoc

# Pull Request Review Comments

## Overview
- **Purpose of the PR**:
    - [/ ] Bug fix
    - [/ ] Refactoring

## Specific Areas for Verification
- Please specify any particular requests or questions for the reviewer here.

## Suggestions/Concerns
- If you have any suggestions or concerns, please mention them here.

---

_**Additional Comments for the Reviewer (Optional)**_

- Add any additional comments or information for the reviewer here.

2024-10-03 08:38 UTC, edward-stalley-work reviewed
Looks goo Ian thank you.
Just a few small changes.

Would it also be possible to do the same implementation for the edit screen.
So you can only select business divisions based on the company?
In list column can we change the column header order.
Eg.   `|company name| business division| created by`

2024-10-03 08:38 UTC, edward-stalley-work commented on backend/api/urls.py
> +    path("business-divisions/", views.CompaniesWithBusinessDivisions.as_view(), name="companies-with-business-division"), #url for filtering the bussiness division from the selected company
Spelling - please change to this: (remove extra 's')

#url for filtering the business division from the selected company

2024-10-03 08:38 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +
can remove this space

2024-10-03 08:38 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +        // setBusinessSelection(resBusinessDivisions.payload)
do we need this comment code?
if not please remove!

2024-10-03 08:38 UTC, edward-stalley-work commented on client/src/pages/Employees/EmployeesRegistration.tsx
>      const [businessSelection, setBusinessSelection] = useState<any>([])
could this and all related code be renamed to businessDivisionSelection?

2024-10-03 08:49 UTC, ian-bpoc commented
> Looks good Ian - thank you. Just a few small changes.
> 
> Would it also be possible to do the same implementation for the edit screen. So you can only select business divisions based on the company? In list column can we change the column header order. Eg. `|company name| business division| created by`

maybe i can suggest Ed to create new ticket for the screen, in order also to avoid more conflicts with my branch, since it might be behind from the develop

2024-10-03 08:58 UTC, ian-bpoc commented on backend/api/urls.py
> +    path("business-divisions/", views.CompaniesWithBusinessDivisions.as_view(), name="companies-with-business-division"), #url for filtering the bussiness division from the selected company
fixed

2024-10-03 08:59 UTC, ian-bpoc commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +
fixed

2024-10-03 08:59 UTC, ian-bpoc commented on client/src/pages/Employees/EmployeesRegistration.tsx
> +        // setBusinessSelection(resBusinessDivisions.payload)
fixed

2024-10-03 08:59 UTC, ian-bpoc commented on client/src/pages/Employees/EmployeesRegistration.tsx
>      const [businessSelection, setBusinessSelection] = useState<any>([])
fixed

2024-10-04 00:25 UTC, edward-stalley-work requested changes
One small edit thank you Ian

2024-10-04 00:25 UTC, edward-stalley-work commented on backend/api/urls.py
> +    path("business-division/", views.CompaniesWithBusinessDivisions.as_view(), name="companies-with-business-division"),
The comment was fine - I think it was helpful actually.
Please put the comment back with the spelling mistake fixed.

bussiness → business

2024-10-04 00:49 UTC, edward-stalley-work commented on backend/api/urls.py
> +    path("business-division/", views.CompaniesWithBusinessDivisions.as_view(), name="companies-with-business-division"),
fixed

2024-10-04 00:50 UTC, merged