implemented project crud and list with validations
carrieayu/bop pull request #159
Opened 2024-10-03 09:23 UTC by merlouduron

# Pull Request Review Comments

## Overview
- **Purpose of the PR**:
    - [ ] Feature addition
    - [ ] Bug fix
    - [ ] Refactoring
    - [ ] Documentation update
    - [ ] Other (please specify below)

## Specific Areas for Verification
- Please specify any particular requests or questions for the reviewer here.

## Suggestions/Concerns
- If you have any suggestions or concerns, please mention them here.

---

_**Additional Comments for the Reviewer (Optional)**_

- Add any additional comments or information for the reviewer here.

2024-10-04 02:30 UTC, edward-stalley-work requested changes
Thank you Merlou, please see comments.

2024-10-04 02:30 UTC, edward-stalley-work commented on client/src/pages/Projects/ProjectsListAndEdit.tsx
> +                                    <RiDeleteBin6Fill
trash bin icon is black instead of red
<img width="89" alt="Screenshot 2024-10-04 at 11 09 32" src="https://github.com/user-attachments/assets/64e0e8b2-3ee8-4bd1-a56d-44709113ba68">

2024-10-04 02:30 UTC, edward-stalley-work commented on client/src/pages/Projects/ProjectsListAndEdit.tsx
> +                                    <RiDeleteBin6Fill
Also wrong message on Delete says employee not project!
<img width="410" alt="Screenshot 2024-10-04 at 11 10 02" src="https://github.com/user-attachments/assets/869868d0-297d-4b74-bd6e-98c42d4cd7b1">

2024-10-04 02:30 UTC, edward-stalley-work commented on client/src/pages/Projects/ProjectsRegistration.tsx
> +    })
Please See this ticket. I updated it a little - apologies but I think my logic was off.


https://dattjapan.backlog.com/view/BOP_MANAGEMENT_SYSTEM-68/

2024-10-04 02:30 UTC, edward-stalley-work commented on client/src/pages/Projects/ProjectsRegistration.tsx
> +                        <div className='projectsRegistration_operating-income-div'>
i) classNames do not match values please check ALL classNames and that they match the name in the input.



ii) Using the plural 'expenses' here instead of 'expense'

2024-10-04 02:30 UTC, edward-stalley-work commented on client/src/pages/Projects/ProjectsListAndEdit.tsx
> +                                  {translate('client', language)}
This displays as 'clients'
Lets add the singular to the general_words file.
 
    "clients": "Clients",
    "client": "Client",
    
    ALSO this needs to be fixed
  "businessDivisions": "Business Divisions ",
  "businessDivision": "Business Division",





Same for Business Division

2024-10-04 09:04 UTC, merlouduron commented on client/src/pages/Projects/ProjectsListAndEdit.tsx
> +                                  {translate('client', language)}
Fixed.

2024-10-04 09:04 UTC, merlouduron commented on client/src/pages/Projects/ProjectsRegistration.tsx
> +                        <div className='projectsRegistration_operating-income-div'>
Fixed.

2024-10-04 09:04 UTC, merlouduron commented on client/src/pages/Projects/ProjectsRegistration.tsx
> +    })
Fixed.

2024-10-04 09:04 UTC, merlouduron commented on client/src/pages/Projects/ProjectsListAndEdit.tsx
> +                                    <RiDeleteBin6Fill
Fixed.

2024-10-04 09:05 UTC, merlouduron commented on client/src/pages/Projects/ProjectsListAndEdit.tsx
> +                                      style={{ width: '50px' }}
I just implemented a scrollable since I can't find a way to make it to be viewed as whole. Just a suggestion of mine.

2024-10-04 09:06 UTC, merlouduron commented on client/src/pages/Projects/ProjectsRegistration.tsx
> +
Fixed.

2024-10-04 09:06 UTC, merlouduron commented on client/src/pages/Projects/ProjectsRegistration.tsx
> +                          <label className='projectsRegistration_client'>{translate('projectName', language)}</label>
Fixed.

2024-10-07 00:37 UTC, edward-stalley-work commented on client/src/pages/Projects/ProjectsListAndEdit.tsx
> +                                      style={{ width: '50px' }}
Okay thank you Merlou - let's use that for now!

2024-10-07 00:42 UTC, edward-stalley-work commented on client/src/pages/Projects/ProjectsListAndEdit.tsx
> +                                    <RiDeleteBin6Fill
Lets use this message.

"この案件を削除してもよろしいですか？"

2024-10-07 00:46 UTC, edward-stalley-work requested changes
Thank you Merlou - just this small change.

2024-10-07 00:46 UTC, edward-stalley-work commented on client/src/translations/general_words_jp.json
> +    "deleteProjectMessage": "本当にこのプロジェクトを削除しますか？",
Lets use this message.

"この案件を削除してもよろしいですか？"

2024-10-07 01:16 UTC, merlouduron commented on client/src/pages/Projects/ProjectsListAndEdit.tsx
> +                                    <RiDeleteBin6Fill
Fixed.

2024-10-07 01:44 UTC, merlouduron commented on client/src/translations/general_words_jp.json
> +    "deleteProjectMessage": "本当にこのプロジェクトを削除しますか？",
Fixed.

2024-10-07 02:06 UTC, merged