for 3 tickets
carrieayu/bop pull request #177
Opened 2024-10-20 22:17 UTC by merlouduron

# Pull Request Review Comments

## Overview
- **Purpose of the PR**:
    - [ ] Feature addition
    - [ ] Bug fix
    - [ ] Refactoring
    - [ ] Documentation update
    - [ ] Other (please specify below)

## Specific Areas for Verification
- Please specify any particular requests or questions for the reviewer here.

## Suggestions/Concerns
- If you have any suggestions or concerns, please mention them here.

---

_**Additional Comments for the Reviewer (Optional)**_

- Add any additional comments or information for the reviewer here.

2024-10-21 06:55 UTC, edward-stalley-work requested changes
I was not sure if you had 100% finished but I took a quick look anyway.
please see comments.

2024-10-21 06:55 UTC, edward-stalley-work commented on client/src/pages/ResetPassword/ResetPassword.tsx
>              alert("Password has been resetted");
Please change to:
→ ”Password has been reset."

2024-10-21 06:55 UTC, edward-stalley-work commented on client/src/pages/ResetPassword/ResetPassword.tsx
>              alert("Password has been resetted");
Is it possible to also use the modals that Joshua created and that are being used for all other messages?

2024-10-21 06:55 UTC, edward-stalley-work commented on client/src/pages/ResetPassword/ResetPassword.tsx
>              alert("Password has been resetted");
Once the Password has been reset we should automatically move to login screen after a second or two.
As there is no link/tab to move to login from this screen.

2024-10-21 06:55 UTC, edward-stalley-work commented on client/src/reducers/card/cardSlice.ts
> +        state.totalGrossProfit = getSum(action?.payload?.map((card) => Number(card.ordinary_profit)))
i think we need to change ordinary_profit to ordinary_income.

2024-10-21 06:55 UTC, edward-stalley-work commented on client/src/reducers/card/cardSlice.ts
>          state.isLoading = true
I am not 100% sure myself so I would like to discuss these values with you. We need them for the planning page as well so I would just like to make sure we are displaying correct values.

2024-10-23 03:28 UTC, merlouduron commented on client/src/pages/ResetPassword/ResetPassword.tsx
>              alert("Password has been resetted");
The message for resetting the password has been updated.
It now uses modals like other pages.
It also navigates to the login page after successfully resetting the password.

2024-10-23 03:29 UTC, merlouduron commented on client/src/reducers/card/cardSlice.ts
> +        state.totalGrossProfit = getSum(action?.payload?.map((card) => Number(card.ordinary_profit)))
I will update this after the completion of the planning page.

2024-10-23 03:29 UTC, merlouduron commented on client/src/reducers/card/cardSlice.ts
>          state.isLoading = true
I will update this after the completion of the planning page.

2024-10-29 01:50 UTC, edward-stalley-work requested changes
Thank you Merlou please see comments

2024-10-29 01:50 UTC, edward-stalley-work commented on client/src/pages/ResetPassword/ResetPassword.tsx
> -import React, { useState } from "react";
Currently I am no receiving an email to reset password.
It did work previously. Can you doublecheck it is working your end? 

I am using my email for the user in auth_user table.
It says it sends - however my inbox does not have a message.

<img width="712" alt="Screenshot 2024-10-29 at 10 33 47" src="https://github.com/user-attachments/assets/24405d86-cf66-42c9-946f-dd4b5263f18d">

Previously I successfully got this email.

<img width="424" alt="Screenshot 2024-10-29 at 10 34 40" src="https://github.com/user-attachments/assets/c48855c5-0c51-4d54-b3c1-41fdb1d972bd">

2024-10-29 01:50 UTC, edward-stalley-work commented on client/src/reducers/graph/graphSlice.ts
> +  totalOperatingProfitByDate: Record<string, number>
For now to keep it in line with name in other parts of code and　
→totalOperatingIncomeByDate

Please adjust  any related code in this file. Also in Dashboard.tsx as well

2024-10-29 01:50 UTC, edward-stalley-work commented on client/src/reducers/graph/graphSlice.ts
> +  totalNetProfitPeriodByDate: Record<string, number>
totalNetProfitPeriodByDate → totalCumulativeOrdinaryIncome

Please adjust  any related code in this file. Also in Dashboard.tsx as well

2024-10-29 02:54 UTC, merlouduron commented on backend/api/models.py
> +    ordinary_income = models.DecimalField(max_digits=12, decimal_places=2, default=0.0)
Fixed.

2024-10-29 02:56 UTC, merlouduron commented on client/src/pages/ResetPassword/ResetPassword.tsx
> -import React, { useState } from "react";
For this one, if it doesn't exist on the inbox, please do check on spam folder. If still doesn't exist, the problem is on the software used. I've tested my email and it also rejected. Will probably use another software.

2024-10-29 02:56 UTC, merlouduron commented on client/src/reducers/graph/graphSlice.ts
> +  totalOperatingProfitByDate: Record<string, number>
Fixed.

2024-10-29 02:56 UTC, merlouduron commented on client/src/reducers/graph/graphSlice.ts
> +  totalNetProfitPeriodByDate: Record<string, number>
Fixed.

2024-10-29 03:59 UTC, edward-stalley-work commented on client/src/pages/ResetPassword/ResetPassword.tsx
> -import React, { useState } from "react";
still does no not receive an email (not in inbox or spam).

It used to work - did the mail software you are using change?

2024-10-29 04:01 UTC, edward-stalley-work reviewed
thank you merlou - please see new comments.

The email still does not work unfortunately.

2024-10-29 06:04 UTC, edward-stalley-work commented on client/src/pages/ResetPassword/ResetPassword.tsx
>              alert("Password has been resetted");
Due to issues with mail software this no longer works and will be tackled in another ticket once live server is up and running.

2024-10-29 06:05 UTC, edward-stalley-work commented on client/src/pages/ResetPassword/ResetPassword.tsx
> -import React, { useState } from "react";
Due to issues with mail software this no longer works and will be tackled in another ticket once live server is up and running.

2024-10-29 06:05 UTC, edward-stalley-work approved these changes

2024-10-29 06:05 UTC, merged