ticket 145
carrieayu/bop pull request #216
Opened 2024-11-19 06:59 UTC by merlouduron

# Pull Request Review Comments

## Overview
- **List of finished task**:
    - [ ] Added CRUD function
    - [ ] Add overwrite function
    - [ ] Fix SCSS and classnames
    - [ ] Added search function
    - [ ] Disabled project_type, client and business_division inputs.

## Specific Areas for Verification
- Please specify any particular requests or questions for the reviewer here.

## Suggestions/Concerns
- If you have any suggestions or concerns, please mention them here.

---

_**Additional Comments for the Reviewer (Optional)**_

- Add any additional comments or information for the reviewer here.

2024-11-20 09:12 UTC, merlouduron commented on client/src/translations/financial_words_jp.json
> +  "projectSalesResults" : "プロジェクト売上実績",
Fixed

2024-11-20 09:12 UTC, merlouduron commented on client/src/translations/financial_words_jp.json
> +  "projectSalesResultsList": "案件売上実績一覧",
Fixed

2024-11-20 09:12 UTC, merlouduron commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
> +                                    {translate('projectSalesResultsId', language)}
Fixed

2024-11-20 09:12 UTC, merlouduron commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsRegistration.tsx
> +                              <option value=''>-- Reset --</option>
Fixed.

2024-11-21 00:29 UTC, edward-stalley-work commented on client/src/translations/financial_words_jp.json
> +  "projectSalesResultsList": "案件売上実績一覧",
Comma was left in - please remove! Edit & List Screen

案件売上実績編集,

<img width="187" alt="Screenshot 2024-11-21 at 09 29 13" src="https://github.com/user-attachments/assets/5ad6d988-835f-467d-b617-d4cb22d5a238">

2024-11-21 00:57 UTC, edward-stalley-work commented on client/src/translations/financial_words_jp.json
> +  "projectSalesResultsList": "案件売上実績一覧",
Also I know its not this ticket but could you fix thiese please!

1.
expensesEdit

<img width="444" alt="Screenshot 2024-11-21 at 09 56 09" src="https://github.com/user-attachments/assets/dcfabf7a-e28d-449a-9cfd-5d878589e9ad">

2. Remove Space in between kanji.
<img width="166" alt="Screenshot 2024-11-21 at 09 56 41" src="https://github.com/user-attachments/assets/f6e4d8f4-19e8-4b9c-88c2-7a79cdaf4802">

3. Add an 's' to result in "Expense Result" in English Mode
<img width="510" alt="Screenshot 2024-11-21 at 09 57 08" src="https://github.com/user-attachments/assets/0883f154-c3f0-475d-b22c-64cf7d57a193">

2024-11-21 01:22 UTC, edward-stalley-work requested changes
Please see new comments. Just some small changes.

2024-11-25 01:10 UTC, edward-stalley-work commented on client/src/translations/financial_words_jp.json
> +  "projectSalesResultsList": "案件売上実績一覧",
Fixed

2024-11-25 01:33 UTC, edward-stalley-work requested changes
Please see comments

2024-11-25 01:33 UTC, edward-stalley-work commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsRegistration.tsx
> +                            <option value=''></option>
May be better to add  "Select Year" in Japanese and English.

年選択

2024-11-25 01:33 UTC, edward-stalley-work commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsRegistration.tsx
> +                            <option value=''></option>
May be better to add  "Select Month" in Japanese and English.

月選択

2024-11-25 01:33 UTC, edward-stalley-work commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsRegistration.tsx
> +                              <option value=''></option>
May be better to add  "Select Project" in Japanese and English.

案件選択

2024-11-25 01:33 UTC, edward-stalley-work commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsRegistration.tsx
> +                              <option value=''></option>
Also, when you select a project then go back and deselect the other inputs stay filled.
They need to be cleared.

Example:
<img width="1140" alt="Screenshot 2024-11-25 at 10 23 03" src="https://github.com/user-attachments/assets/e7d5c647-d950-49b0-9919-704b2a4b3982">

2024-11-25 01:33 UTC, edward-stalley-work commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
> +    deleteProjectSalesResults(deleteProjectsId, token)
When delete is pressed the record remains on page until a manual refresh.

Record was deleted but still displayed.

<img width="1106" alt="Screenshot 2024-11-25 at 10 28 35" src="https://github.com/user-attachments/assets/a95fcc02-cdbc-405d-841c-0bad3255448a">

2024-11-25 01:33 UTC, edward-stalley-work commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
> +    const getModifiedFields = (original, updated) => {
No validation check on empty inputs.
This is fine however as I will pull this into my ticket and add the updated validation for front end I have been working on.

-Ed will handle in another ticket

2024-11-25 03:00 UTC, merlouduron commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsRegistration.tsx
> +                            <option value=''></option>
Fixed

2024-11-25 03:00 UTC, merlouduron commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsRegistration.tsx
> +                            <option value=''></option>
Fixed.

2024-11-25 04:28 UTC, merlouduron commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
> +    deleteProjectSalesResults(deleteProjectsId, token)
Fixed.

2024-11-25 04:28 UTC, merlouduron commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
> +    const getModifiedFields = (original, updated) => {
Thank you Ed. 🙇

2024-11-25 06:04 UTC, edward-stalley-work commented on client/src/translations/financial_words_jp.json
> +  "projectSalesResultsList": "案件売上実績一覧",
The above has not been addressed.
<img width="219" alt="Screenshot 2024-11-25 at 15 01 02" src="https://github.com/user-attachments/assets/bc7fa913-a0b3-4ac0-95e8-28864febc981">

2024-11-25 06:07 UTC, edward-stalley-work commented on client/src/translations/financial_words_jp.json
> +  "projectSalesResultsList": "案件売上実績一覧",
Please fix the text 

<img width="268" alt="Screenshot 2024-11-25 at 15 07 31" src="https://github.com/user-attachments/assets/867abeb8-dc50-480b-903e-fdfa49c82197">

<img width="269" alt="Screenshot 2024-11-25 at 15 07 19" src="https://github.com/user-attachments/assets/42b8ab13-5e04-4206-bb63-aa1b30f47982">

2024-11-25 06:26 UTC, edward-stalley-work commented on client/src/translations/financial_words_jp.json
> +  "projectSalesResultsList": "案件売上実績一覧",
fixed

2024-11-25 06:27 UTC, edward-stalley-work approved these changes

2024-11-25 06:27 UTC, merged