Feature/bop/ticket 146
carrieayu/bop pull request #217
Opened 2024-11-20 03:25 UTC by merlouduron

# Pull Request Review Comments

## Overview
- **Purpose of the PR**:
    - [ ] Feature addition
    - [ ] Bug fix
    - [ ] Refactoring
    - [ ] Documentation update
    - [ ] Other (please specify below)

## Specific Areas for Verification
- Please specify any particular requests or questions for the reviewer here.

## Suggestions/Concerns
- If you have any suggestions or concerns, please mention them here.

---

_**Additional Comments for the Reviewer (Optional)**_

- Add any additional comments or information for the reviewer here.

2024-11-27 02:06 UTC, edward-stalley-work reviewed
Please see comments

2024-11-27 02:06 UTC, edward-stalley-work commented on backend/api/models.py
> +    project = models.ForeignKey(Projects, on_delete=models.CASCADE, null=True)
I think for the moment , the project should be linked to the "project" in "project_sales_results table".
If you see any issues or problems with this or need to discuss it please talk to me.

<img width="347" alt="Screenshot 2024-11-27 at 11 04 29" src="https://github.com/user-attachments/assets/e85cfdde-289c-4bf1-9b35-12622839eccb">

2024-11-27 02:06 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.tsx
> +                                  <option value=''></option>
Same comment as in model.

I think for the moment , the project should be linked to the "project" in "project_sales_results table".
If you see any issues or problems with this or need to discuss it please talk to me.

<img width="347" alt="Screenshot 2024-11-27 at 11 04 29" src="https://github.com/user-attachments/assets/e85cfdde-289c-4bf1-9b35-12622839eccb">

2024-11-27 15:10 UTC, merlouduron commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsRegistration.tsx
> +                { labelKey: 'employeeExpensesResults', tabKey: 'employeeExpensesResults' },
Fixed.

2024-11-27 15:11 UTC, merlouduron commented on client/src/pages/EmployeeExpensesResults/EmployeeExpenseResultsList.tsx
> +  const handleDelete = () => {
Fixed.

2024-11-27 15:11 UTC, merlouduron commented on client/src/pages/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.tsx
> +  const handleSubmit = async (e) => {
Fixed.

2024-11-27 15:12 UTC, merlouduron commented on client/src/pages/EmployeeExpensesResults/EmployeeExpenseResultsList.tsx
> +                                                        {project.employee_salary}
Fixed.

2024-11-28 02:13 UTC, merlouduron commented on backend/api/models.py
> +    project = models.ForeignKey(Projects, on_delete=models.CASCADE, null=True)
I tried implementing it but might be a bit complicated. Since we need the data from Projects. If we use the ProjectSalesResults we need to connect it to Project table. If we are really required to use ProjectSalesResult as foreign key, then we can do that on other ticket but as of now and more simpler way is to use Project table.

2024-11-28 02:13 UTC, merlouduron commented on client/src/pages/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.tsx
> +                                  <option value=''></option>
Same as above.

2024-11-28 03:32 UTC, edward-stalley-work requested changes
Please see comments

2024-11-28 03:32 UTC, edward-stalley-work commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
> +                  { labelKey: 'employeeExpensesResults', tabKey: 'employeeExpensesResults' },
Issue: English Text Does Not Fit in Buttons.

Can you add another Name to the translation JSON file?
Add "short" to the names: for example - employeeExpensesResultsShort: "Employee Exp. Res."

Display Like this:
<img width="641" alt="Screenshot 2024-11-28 at 12 04 11" src="https://github.com/user-attachments/assets/f5b44fef-02d0-42c7-9a7b-7c82cc75c7d9">

2024-11-28 03:32 UTC, edward-stalley-work commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
> +                  { labelKey: 'employeeExpensesResults', tabKey: 'employeeExpensesResults' },
Issue - Tab is not working correctly - When Project Sales Results is selected sometimes the page does not actually change.

How to see bug:
1. Select Employee Expense Result Tab
2. Select Project Sales Results Tab

<img width="1410" alt="Screenshot 2024-11-28 at 12 08 23" src="https://github.com/user-attachments/assets/36958f9c-ce6c-4871-a976-5e800b3be26c">

2024-11-28 03:32 UTC, edward-stalley-work commented on backend/api/models.py
> +    project = models.ForeignKey(Projects, on_delete=models.CASCADE, null=True)
So after more thought because this is a separate set of data I think we have no choice but to link it to project sales results table.

project → employee expense → planning page
project sales results → employee expense results → results page

Case:
- We have "Test Project One" in both project tables but the values are totally different.
- In the employee expense result table  if the employee is not linked to the projects_results table then the results screen will have issues...

We may need to have a call about this.



IDEA FOR FUTURE:
Although I do think this would be more ideal design.

Project should be seperated from all amounts and just have basic data.

mst_projects (name, type, client, business division )
projects_planning (year, month, financial values)
projects_results  (year, month, financial values)

2024-11-28 03:32 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpenses/EmployeeExpensesList.tsx
> +    const [deletedId, setDeletedId] = useState<any>(null)
On this screen the title seems to be broken for Edit

<img width="493" alt="Screenshot 2024-11-28 at 12 25 43" src="https://github.com/user-attachments/assets/5ca8f47c-3eab-4d1c-8943-1bfd88b5979f">

2024-11-28 03:32 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.tsx
> +                                  <option value=''></option>
Need further discussion.

2024-11-28 04:18 UTC, merlouduron commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
> +                  { labelKey: 'employeeExpensesResults', tabKey: 'employeeExpensesResults' },
Fixed.

2024-11-28 04:18 UTC, merlouduron commented on client/src/pages/EmployeeExpenses/EmployeeExpensesList.tsx
> +    const [deletedId, setDeletedId] = useState<any>(null)
Fixed.

2024-11-28 05:32 UTC, edward-stalley-work requested changes
See comment

2024-11-28 05:32 UTC, edward-stalley-work commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
> +                  { labelKey: 'employeeExpensesResultsShort', tabKey: 'employeeExpensesResults' },
In this screen I just noticed this. Please remove comma.
<img width="195" alt="Screenshot 2024-11-28 at 14 31 52" src="https://github.com/user-attachments/assets/a43cb468-4669-41a3-9493-704369eea761">

2024-11-29 02:14 UTC, edward-stalley-work commented on backend/api/models.py
> +    project = models.ForeignKey(Projects, on_delete=models.CASCADE, null=True)
Fixed

2024-11-29 02:14 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.tsx
> +                                  <option value=''></option>
Discussed and Fixed.

2024-11-29 02:15 UTC, edward-stalley-work commented on client/src/pages/ProjectSalesResults/ProjectSalesResultsListAndEdit.tsx
> +                  { labelKey: 'employeeExpensesResultsShort', tabKey: 'employeeExpensesResults' },
I will handle in another ticket.

2024-11-29 03:05 UTC, edward-stalley-work requested changes
Please see comments

2024-11-29 03:05 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.tsx
> +    // # Client Side Validation
I do not seem to be getting the error messages any more...

2024-11-29 03:06 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.tsx
> +                                    <option key={year} value={year}>
In regard to the above as it related to original employee expenses screens as well we can leave it for now.
I have asked Ishigamori san and added it to the ISSUES sheet so it can be handled in another ticket.

2024-11-29 07:29 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.tsx
> +                                    <option key={year} value={year}>
This will be handled in a new ticket.

2024-11-29 07:30 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpensesResults/EmployeeExpensesResultsRegistration.tsx
> +                                    <option key={year} value={year}>
Short term : limit pulldowns to dates exising for selected project
Long term: make 3 tables projects, projects_planning, projects_results

2024-11-29 07:44 UTC, edward-stalley-work approved these changes

2024-11-29 07:44 UTC, merged