Origin/fix/bop 158
carrieayu/bop pull request #230
Opened 2024-12-09 07:13 UTC by takuyakuramatsu

# Pull Request Review Comments

## Overview
- **Purpose of the PR**:
    - [ ] ISSUE (99) Make all pulldowns the same. ( すべてのプルダウンを同じにする)
ISSUE (99) Either have "Select Year" etc. in Registration Screens. (登録画面に「年度選択」等がある)
ISSUE (99) No empty space at top of pull down in Edit Screens if value cannot be empty. (編集画面のプルダウンで、値を空にできない場合、上部に空白がない。)

## Specific Areas for Verification
- Please specify any particular requests or questions for the reviewer here.

## Suggestions/Concerns
- If you have any suggestions or concerns, please mention them here.

---

_**Additional Comments for the Reviewer (Optional)**_

- Add any additional comments or information for the reviewer here.

2024-12-10 00:15 UTC, edward-stalley-work commented
下記のプルダウンの既定追加：

**画面**：             **プルダウン**

1. 案件登録： 受注事業部 (受注事業部選択 /  Select Business Division)
2. 人件費登録: 案件 (案件選択 / Select Project)
3. 案件人件費実績登録: 案件 (案件選択 / Select Project)
4. 従業員登録:  会社名   +　受注事業部 ( 会社選択 / Select Company + 受注事業部選択 /  Select Business Division)
5. 受注事業部登録: 会社名 (英語しかない)  ( 会社選択 / Select Company)

2024-12-10 00:17 UTC, edward-stalley-work commented
受注事業部登録

統一ために "Select a Company" → ”Select Company" に更新するの良いいかもしれません。

<img width="514" alt="Screenshot 2024-12-10 at 09 16 26" src="https://github.com/user-attachments/assets/b17c7ef7-46e8-4ca2-9041-13e74586e4a0">

2024-12-10 00:33 UTC, edward-stalley-work requested changes
実装ありがとうございます。コメントをご都合にある時にご確認お願いいたします。

2024-12-10 00:33 UTC, edward-stalley-work commented on client/src/pages/CostOfSales/CostOfSalesRegistration.tsx
> +  const years = [2024, 2025]
全部の登録画面同じ「年」を使用するので将来的なアップデートを容易にするためにも、一カ所に定義しておいた方がいいのかもしれない。

例えば：

constants.ts

```
// # Component Constants

export const years = [2024,2025]
```

では、これをコンポーネントにインポートするのか？

`import { YEARS } from '../../constants'
`

いかがでしょうか？

2024-12-10 00:38 UTC, takuyakuramatsu commented on client/src/pages/CostOfSales/CostOfSalesRegistration.tsx
> +  const years = [2024, 2025]
承知しました。
共通化するのは良いと思います。

2024-12-10 01:00 UTC, takuyakuramatsu commented on client/src/pages/CostOfSalesResults/CostOfSalesResultsRegistration.tsx
> +                            <option value=''>{translate('selectMonth', language)}</option>
＞ 2024年を選択した場合、(4-12月)しか選択できない。
＞ 2025年を選択すれば、(1-3月)しか選択できない。

プルダウンメニューでしたら
上記の考えでよいと思います。

2024-12-10 02:00 UTC, takuyakuramatsu commented on client/src/pages/CostOfSalesResults/CostOfSalesResultsRegistration.tsx
> +                            <option value=''>{translate('selectMonth', language)}</option>
Edさん、お疲れ様です。

上記について、途中まで実装を進め、実装方法を考えました。

例えば、
「年」がシステム年と同一ならば、「月」は、4～12
「年」がシステム年＋１ならば、「月」は1～3
というロジックだと、いかがでしょうか？

これだと、ロジックを変えずに、来年も再来年も機能すると考えました。

2024-12-10 02:13 UTC, edward-stalley-work commented on client/src/pages/CostOfSalesResults/CostOfSalesResultsRegistration.tsx
> +                            <option value=''>{translate('selectMonth', language)}</option>
倉松さん、ありがとうございます。
それは良いと思います。

2024-12-10 04:47 UTC, edward-stalley-work reviewed
コメント

2024-12-10 04:57 UTC, takuyakuramatsu commented on client/src/pages/Projects/ProjectsRegistration.tsx
> +
Edさん、確認いたしました。

会計年度に関するコメント。たしかに↑のとおりだと思います。
ただ、今、「年度を切り替える仕組み」が無いので、現状でできる範囲だと

■2024/01/01～2025/03/31
2024 → (4-12)
2025 → (1 -3)

■2025/04/01～2026/03/31
2025 → (4-12)
2026 → (1 -3)

という選択になるかと思いました。
さきほど「システム年を使って」という形で記述しましたが、
正確には「システム年の4月1日を区切りに」という意味でした。

いかがでしょうか。

2024-12-10 05:19 UTC, edward-stalley-work commented on client/src/pages/Projects/ProjectsRegistration.tsx
> +
倉松さん、回答ありがとうございます。

承知いたしました。
では 倉松さんが言った通りにしましう。

2024-12-17 08:30 UTC, takuyakuramatsu commented
対応漏れがありまして恐れ入ります。
「プルダウンの既定追加」について、対応完了してコミットいたしました。
ご確認の程よろしくお願いいたします。

2024-12-17 08:37 UTC, edward-stalley-work requested changes
よろしくお願いいたします!

2024-12-17 08:37 UTC, edward-stalley-work commented on client/src/pages/BusinessDivisions/BusinessDivisionsRegistration.tsx
> +                            <option value=''>{translate('selectCompany', language)}</option>
言語変更してもプルダウンいつも英語で表示されています。

下記の画面は日本語です。

”会社名選択”の代わりに"Select a Company"表示してしましました!

細かいことですが、元もとあるコードは"Select a Company"ですが、倉松さんの実装いただいたプルダウン統一ために"Select Company"に変更するのは良いいです！　（”a"抜くということです）

会社名選択 / Select Company

<img width="1489" alt="Screenshot 2024-12-17 at 17 28 24" src="https://github.com/user-attachments/assets/7db9a1c5-3d42-4843-b935-71721a394655" />

2024-12-18 02:22 UTC, edward-stalley-work commented on client/src/pages/BusinessDivisions/BusinessDivisionsRegistration.tsx
> +                            <option value=''>{translate('selectCompany', language)}</option>
手元で再確認いたしました。
なんとなく問題が発生していません。

おそらく、私の方で何らかの不具合があったのかもしれません。とにかく、今は問題なくなりました。

2024-12-18 07:04 UTC, edward-stalley-work approved these changes

2024-12-18 07:04 UTC, merged