fixed employee expense result dropdown
carrieayu/bop pull request #238
Opened 2024-12-16 09:32 UTC by merlouduron

# Pull Request Review Comments

## Overview
- **Purpose of the PR**:
    - [ ] 

## Specific Areas for Verification
- Please specify any particular requests or questions for the reviewer here.

## Suggestions/Concerns
- If you have any suggestions or concerns, please mention them here.

---

_**Additional Comments for the Reviewer (Optional)**_

- Add any additional comments or information for the reviewer here.

2024-12-17 06:52 UTC, edward-stalley-work reviewed
Same content as the meeting.
Just leave a done comment when finished!

2024-12-17 06:52 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
> +                                  {projects.map((month, idx) => (
As discussed in the meeting.
We need to make sure the month and year display only for dates that exist for that project.

2024-12-17 08:49 UTC, edward-stalley-work requested changes
Please See comments

2024-12-17 08:49 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
> +import { getFilteredEmployeeExpense } from '../../api/EmployeeExpenseEndpoint/FilterGetEmployeeExpense';
on HandleSubmit I am getting an error and cannot successfully create any records.
I tried with multiple projects and dates and it always returned an error.

Do I need to delete migrations etc?

<img width="1253" alt="Screenshot 2024-12-17 at 17 45 41" src="https://github.com/user-attachments/assets/f14a88f1-36a3-4eee-82be-82a2a188c16c" />

2024-12-17 09:10 UTC, merlouduron commented on client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
> +                                  {projects.map((month, idx) => (
Done.

2024-12-17 09:11 UTC, merlouduron commented on client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
> +import { getFilteredEmployeeExpense } from '../../api/EmployeeExpenseEndpoint/FilterGetEmployeeExpense';
Apologies for this one. The payload is different so I made some adjustments on `views.py`. It should be working now. 
Fixed.

2024-12-18 00:25 UTC, edward-stalley-work requested changes
Please see new comments.

2024-12-18 00:25 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
> +
can delete this added space

2024-12-18 00:25 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
> +
can delete this console log

2024-12-18 00:25 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
> +import { getFilteredEmployeeExpense } from '../../api/EmployeeExpenseEndpoint/FilterGetEmployeeExpense';
Thank you - it works now.
However I get same error on results screen.
The same changes may need to be made there as well.

<img width="1168" alt="Screenshot 2024-12-18 at 09 22 59" src="https://github.com/user-attachments/assets/bc6d9235-b69f-4889-a75b-2eca738e3d07" />

2024-12-18 01:37 UTC, merlouduron commented on client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
> +
Fixed.

2024-12-18 01:37 UTC, merlouduron commented on client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
> +
Fixed.

2024-12-18 01:44 UTC, merlouduron commented on client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
> +import { getFilteredEmployeeExpense } from '../../api/EmployeeExpenseEndpoint/FilterGetEmployeeExpense';
Fixed.

2024-12-18 01:56 UTC, edward-stalley-work commented on client/src/pages/EmployeeExpenses/EmployeeExpensesRegistration.tsx
> +
the whitspace still exists (green area)
Need to use backspace until cursor is at left side!

2024-12-18 08:26 UTC, edward-stalley-work approved these changes

2024-12-18 08:26 UTC, merged